### ISSUE TITLE
/stats endpoint

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db-pinner#14]
This would be a basic HTTP endpoint that can be turned on or off via config, and would contain useful stats like:

1. How many DBs are pinned?
2. What is the size of each DB?
3. When was each DB last replicated / used?

Open to more stats here as well

**Comment by skybondsor** [comment]
+ Weekly and monthly snapshots so we can track the size of individual DBs over time

**Comment by skybondsor** [comment]
Also, please don't literally do log.education/stats because those are Apache logs currently
