### ISSUE TITLE
Bundle OrbitDB Control Center?

### ISSUE THREAD

**Issue by aphelionz** [orbitdb/orbit-db-pinner#7]
Because why not :D 

https://github.com/haadcode/orbit-db-control-center

**Comment by Jon-Biz** [comment]
This would be awesome. I'm looking into it.

**Comment by techster10173** [comment]
@Jon-Biz has there been any updates to this?

**Comment by haydenyoung** [comment]
Closing as orbitdb control center probably needs to be re-invigorated to include latest OrbitDB version.
